### ISSUE TITLE
Allow running even when there are not litra devices connected

### ISSUE THREAD

**Issue by aeirola** [timrogers/litra-autotoggle#2]
Hi, loving the autotoggle service, but having some issues with my hot-plugging setup where my laptop is occasionally disconnected from my desk setup that contains the litra light. It seems that the litra-autotoggle process exists in case the webcam is turned on while there are no litra lights connected. The log line seems to be

```
HID error occurred: hidapi error: Device is disconnected
```

Similarly, when starting the service with no device connected it will also fail to start. In that case the log error is

```
Device not found.
```

Running the tool as a hombrew service, for which it would be really handy to have the lights turn on when available, but do nothing in case I'm not at my desk setup.

Would it be possible to allow running the services with no litra devices connected? At least as an configurable parameter.

Thanks for making the life of video-conferencing a tad more enjoyable :heart:

**Comment by timrogers** [comment]
I think this is a very sensible idea - leave it with me ✨
